---

jails:

  - name : nginx
    exec : jails/nginx.sh

  - name : postgres
    exec : jails/postgres.sh

  - name : postgrest
    exec : jails/postgrest.sh

  - name : api
    exec : jails/api.sh

  - name : tester
    exec : jails/tester.sh

steps:

  - name : Build packages
    exec : steps/package.sh

  - name : Run tests
    exec : steps/test.sh

  - name : Deploy
    exec : steps/deploy.sh
